#9 rest client impl
i-Cell-Mobilsoft-Open-Source/backend-sampler pull request #10
Opened 2022-08-15 16:56 UTC by czenczl

-classic rest client coffee alapokon
-todo-k ahol a deltaspike-ot le kell valtani

2022-08-15 18:33 UTC, speter555 approved these changes

2022-08-16 07:31 UTC, petrenyi-mark approved these changes

2022-08-16 09:56 UTC, rombow requested changes

2022-08-16 09:56 UTC, rombow commented on sample-quarkus/sample-quarkus-rest-service/src/main/java/hu/icellmobilsoft/sampler/sample/quarkus/restservice/rest/api/ISampleRestClient.java
> +public interface ISampleRestClient {
Ezt jo lenne szinkronban tartani a jelenlegi ISampleRest-el. Valoszinu egy az egyben jo is

2022-08-16 22:37 UTC, bucherarnold approved these changes

2022-08-22 07:08 UTC, rombow approved these changes

2022-08-22 09:13 UTC, bucherarnold approved these changes

2022-08-23 08:04 UTC, merged