#21 grpc
i-Cell-Mobilsoft-Open-Source/backend-sampler pull request #22
Opened 2023-01-31 15:01 UTC by czenczl

minta implementacio

2023-01-31 15:23 UTC, rombow requested changes

2023-01-31 15:23 UTC, rombow commented on common/common-grpc-api/src/main/resources/META-INF/beans.xml
> +      http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd" bean-discovery-mode="annotated">
v4-es verzio van a jakartaEE10-ben (4x lattam)

2023-01-31 15:23 UTC, rombow commented on common/common-grpc-api/pom.xml
> +            <groupId>javax.annotation</groupId>
javax.annotation hova? jakarta?

2023-01-31 15:23 UTC, rombow commented on testsuite/ts-sample/ts-sample-grpc-server/pom.xml
> +                    <artifactId>resteasy-jaxrs</artifactId>
ez mar ugytudom nincs benne

2023-01-31 16:50 UTC, czenczl commented on common/common-grpc-api/pom.xml
> +            <groupId>javax.annotation</groupId>
igen, nincs olyan generator ami nem a package javax.annotation-t hasznalna, ezert kell neki jelenleg

2023-01-31 22:09 UTC, speter555 commented on sample/sample-grpc-server-service/src/main/java/hu/icellmobilsoft/sampler/sample/grpc/server/GrpcServerManager.java
> +    public void addService(Bean<?> bean, ServerBuilder<?> serverBuilder) {
ennek biztos publicnak kell lennie?

2023-02-07 12:22 UTC, rombow commented on common/common-grpc-api/pom.xml
> +            <groupId>javax.annotation</groupId>
Ennek letezik jakarta nevtanos dependencyje nem?

```
<dependency>
   <groupId>jakarta.annotation</groupId>
   <artifactId>jakarta.annotation-api</artifactId>
   <version>1.3.5</version>
</dependency>
```

2023-02-07 12:24 UTC, rombow commented on common/common-grpc-api/src/main/proto/hu/icellmobilsoft/coffee/dto/common/common/hu_icellmobilsoft_coffee_dto_common_common.proto
> +package hu.icellmobilsoft.coffee.dto.common.common;
ez nem generalt fajl?

2023-02-07 12:30 UTC, rombow commented on sample/sample-grpc-server-service/src/main/java/hu/icellmobilsoft/sampler/sample/grpc/server/service/action/SampleGrpcAction.java
> +        } catch (Exception e) {
Ez igy eleg fura...

2023-02-07 12:32 UTC, rombow commented on sample/sample-grpc-server-service/src/main/java/hu/icellmobilsoft/sampler/sample/grpc/server/GrpcServerManager.java
> +    @ConfigProperty(name = "coffee.grpc.server.port", defaultValue = 8199 + "")
GrpcServerConfig?

2023-02-09 13:25 UTC, rombow approved these changes

2023-02-13 07:57 UTC, rombow commented on pom.xml
> +                <activeByDefault>false</activeByDefault>
ezt jo lenne az eredetin hagyni, rahatassal van az egesz projektre nem csak erre a pocra

2023-02-13 09:01 UTC, czenczl commented on pom.xml
> +                <activeByDefault>false</activeByDefault>
rendberakjuk még a kódot, doc-ok még nagyon hiányosak

2023-03-01 07:52 UTC, rombow submitted a review, later dismissed

2023-03-01 07:52 UTC, rombow commented on api/api-grpc/api-grpc-stub-gen/pom.xml
> +			<artifactId>common-grpc-core</artifactId>
hierarchia a csomagokban nem egyertelmu.
Mivel api szinten vagyunk abban nagyon a commonbol nem kellene lennie semminek. A common-grpc-protoc common-grpc-core csomagot at kellene nevezni vagy osszevonni (pl. grpc-core) es helyezni az api szintre vagy api melle

2023-03-01 11:35 UTC, rombow approved these changes

2023-03-02 08:33 UTC, bucherarnold approved these changes

2023-03-03 15:54 UTC, merged