English translation of documentation and documents #62
i-Cell-Mobilsoft-Open-Source/backend-sampler pull request #65
Opened 2023-07-18 13:55 UTC by RolandRozsa

.adoc translation

2023-07-19 06:37 UTC, rombow requested changes

2023-07-19 06:37 UTC, rombow commented on docs/en/migration_v2.adoc
> +The`bom-wf-27 alprojekt` (`bom-wf-27 subproject`) has been created, which tracks the components of WildFly version 27.0.1.Final.
`bom-wf-27 alprojekt` (`bom-wf-27 subproject`)
duplicate in translation

2023-07-19 06:37 UTC, rombow commented on docs/en/migration_v2.adoc
> +include::../dto/pom.xml[lines=34..42]
I think this include needs an extra flag: `include::../../dto/pom.xml[lines=34..42]`, because of the "en/" directory

2023-07-19 06:37 UTC, rombow commented on docs/en/services/grpc.adoc
> +* api-grpc-proto-gen/target/generated-sources/src -> generalt *.proto
generalt -> generated

2023-07-19 06:37 UTC, rombow commented on docs/en/services/grpc.adoc
> +* api-grpc-stub-gen/target/generated-sources -> *.java stub-ok
stub-ok -> stubs

2023-07-19 13:00 UTC, rombow submitted a review, later dismissed

2023-07-21 23:07 UTC, czenczl commented on docs/en/services/grpc.adoc
> +* gRPC kliens sent request
client

2023-07-21 23:07 UTC, czenczl commented on docs/en/services/grpc.adoc
> +.Kliens
Client

2023-07-21 23:08 UTC, czenczl submitted a review, later dismissed

2023-07-23 21:48 UTC, bucherarnold approved these changes

2023-07-26 08:01 UTC, rombow submitted a review, later dismissed

2023-07-26 08:18 UTC, czenczl submitted a review, later dismissed

2023-07-26 10:39 UTC, rombow approved these changes

2023-07-26 10:51 UTC, czenczl approved these changes

2023-09-28 13:37 UTC, bucherarnold approved these changes

2023-09-28 14:18 UTC, merged