Feature/74 kafka service avro message
i-Cell-Mobilsoft-Open-Source/backend-sampler pull request #78
Opened 2023-10-06 10:20 UTC by janosboroczki

2023-10-06 14:03 UTC, rombow requested changes

2023-10-06 14:03 UTC, rombow commented on sample/sample-kafka-service/src/main/java/hu/icellmobilsoft/sampler/sample/kafka/service/action/KafkaPublisher.java
> +            messageEmitter.sendAndAwait(message);
ne keverjuk ossze az avro es a String tipusu kikuldest, legyen legalabb kulon metodusban

2023-10-06 14:03 UTC, rombow commented on sample/sample-kafka-service/src/main/webapp/WEB-INF/web.xml
> +        <param-name>resteasy.preferJacksonOverJsonB</param-name>
ez elegge blocking feltetel lehet a tobbi komponense, tehat valahogy meg kellene oldani hogy ez ne kelljen

2023-10-06 18:57 UTC, czenczl approved these changes

2023-10-06 18:58 UTC, czenczl commented on sample/sample-kafka-service/src/main/webapp/WEB-INF/web.xml
> +    <context-param>
ezt tudjuk melyik dependency hozza be ezt a beallitast?

2023-10-10 10:51 UTC, janosboroczki commented on sample/sample-kafka-service/src/main/webapp/WEB-INF/web.xml
> +    <context-param>
Azt sajnos nem sikerult kideritenem, hogy pontosan hol jon be, de az `avro` es a `kafka-avro-serializer` dependency is valahol beallitja `true`-ra.

2023-10-10 10:56 UTC, janosboroczki commented on sample/sample-kafka-service/src/main/webapp/WEB-INF/web.xml
> +        <param-name>resteasy.preferJacksonOverJsonB</param-name>
Az `avro` es a `kafka-avro-serializer` is beallitja `true`-ra, ennek az az eredmenye, hogy a rest endpointjaink is jackson-nel probalnak serializalni es igy peldaul `LocalDate`-re elhasalunk.

Van esetleg otleted, hogy mi mast tudnank csinalni?

2023-10-12 07:00 UTC, rombow commented on sample/sample-kafka-service/src/main/webapp/WEB-INF/web.xml
> +        <param-name>resteasy.preferJacksonOverJsonB</param-name>
Nem az a baj hogy a kafka serializer nem hasznalja a jsonb-t, nyogodtan mehet jackson-al. Inkabb ott latom a problemat hogy semmi koze nem kellene hogy legyen a rest(easy)hez es annak a json parser beallitasahoz. Ez a jsonb beallitas globalis es default mostmar jo ideje es kozben a kafkanak a resthez nem igazan kell hogy koze legyen

2023-10-12 07:23 UTC, janosboroczki commented on sample/sample-kafka-service/src/main/webapp/WEB-INF/web.xml
> +        <param-name>resteasy.preferJacksonOverJsonB</param-name>
En is hasonlo kovetkeztetesre jutottam, de ha behuzom az avro-t az felulcsapja a default beallitast, es akkor a resteasy is jackson-nel probal serializalni. Ezt kerultem meg azzal, hogy visszaallitottam false-ra ezt a beallitast

2023-10-12 07:55 UTC, rombow commented on sample/sample-kafka-service/src/main/webapp/WEB-INF/web.xml
> +        <param-name>resteasy.preferJacksonOverJsonB</param-name>
esetleg "avro.remove.java.properties" beallitas? https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroSerializerConfig.java#L35

2023-10-12 07:57 UTC, janosboroczki commented on sample/sample-kafka-service/src/main/webapp/WEB-INF/web.xml
> +        <param-name>resteasy.preferJacksonOverJsonB</param-name>
ezt nem talaltam meg, kiprobalom, koszi

2023-10-12 10:00 UTC, czenczl commented on sample/sample-kafka-service/src/main/webapp/WEB-INF/web.xml
> +        <param-name>resteasy.preferJacksonOverJsonB</param-name>
itt jön be https://github.com/confluentinc/schema-registry/blob/master/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java#L19

A resteasy ha talal jackson annotaciot akkor azt fogja aktivalna a resten:
WFLYRS0018: Explicit usage of Jackson annotation in a Jakarta RESTful Web Services deployment; the system will disable Jakarta JSON Binding processing for the current deployment. Consider setting the 'resteasy.preferJacksonOverJsonB' property to 'false' to restore Jakarta JSON Binding.

Ezt a serializaciot nem tudjuk csinalni az avro-rest-es csomag nelkul?

2024-01-29 10:28 UTC, czenczl approved these changes

2024-01-29 10:35 UTC, rombow commented on sample/sample-kafka-service/src/main/webapp/WEB-INF/web.xml
> +        <param-name>resteasy.preferJacksonOverJsonB</param-name>
Osszesitve: bekotott dependency tartalmazza a jackson-t es a resteasy eszreveszi, felul aktivalja a jsonB-t. Ezt nekunk vissza kell allitani default eredeti ertekre.

2024-01-29 10:35 UTC, rombow submitted a review, later dismissed

2024-02-02 17:01 UTC, czenczl approved these changes

2024-02-03 19:20 UTC, speter555 commented on sample/sample-kafka-service/src/main/java/hu/icellmobilsoft/sampler/sample/kafka/service/action/KafkaPublisher.java
> +    public void toKafkaAvro(SampleKafkaDto message) throws BaseException {
Ez a kérdés az összes public metódushoz kérdés: biztos mindenhol lesz értéke a paraméterek ek? Ndm kéne rájuk egy null check, string esetén esetleg egy blank check?

2024-02-08 11:59 UTC, rombow submitted a review, later dismissed

2024-02-15 11:31 UTC, czenczl submitted a review, later dismissed

2024-02-15 12:02 UTC, czenczl approved these changes

2024-02-15 12:05 UTC, rombow approved these changes

2024-02-15 12:06 UTC, merged